"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Heart, Sparkles, Trash2, FolderHeart } from "lucide-react";
import { getFavorites, clearFavorites, FavoriteItem } from "../../lib/db";
import ColorDetails from "../../components/ColorDetails";
import DesignTokenExporter from "../../components/DesignTokenExporter";

export default function FavoritesPage() {
  const [favorites, setFavorites] = useState<FavoriteItem[]>([]);

  const loadFavorites = () => {
    getFavorites().then(setFavorites);
  };

  useEffect(() => {
    loadFavorites();
  }, []);

  const handleClearAll = async () => {
    if (confirm("Are you sure you want to clear all favorited colors?")) {
      await clearFavorites();
      setFavorites([]);
    }
  };

  const favoriteColors = favorites
    .filter((f) => f.type === "color")
    .map((f) => f.value);

  return (
    <div className="space-y-8">
      {/* Header section */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-black tracking-tight text-foreground flex items-center gap-2">
            <Heart className="w-8 h-8 text-rose-500" />
            Favorites Library
          </h2>
          <p className="text-sm text-muted-foreground mt-1.5">
            Manage your saved colors and export them into code snippets.
          </p>
        </div>

        {favorites.length > 0 && (
          <button
            onClick={handleClearAll}
            className="flex items-center gap-2 px-4 py-2 bg-red-500/10 hover:bg-red-500/20 text-red-500 border border-red-500/20 rounded-lg text-xs font-bold transition-colors self-start sm:self-center"
          >
            <Trash2 className="w-4 h-4" />
            Delete All Favorites
          </button>
        )}
      </div>

      {favorites.length > 0 ? (
        <div className="space-y-8 max-w-5xl">
          {/* Colors grid */}
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-500" />
              <h3 className="text-base font-bold text-foreground">Saved Swatches</h3>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              <AnimatePresence>
                {favorites.map((item) => (
                  <motion.div
                    key={item.id}
                    layout
                    exit={{ opacity: 0, scale: 0.95 }}
                    transition={{ duration: 0.15 }}
                  >
                    <ColorDetails color={item.value} onFavoriteChange={loadFavorites} />
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </div>

          {/* Export presets */}
          <div className="space-y-4">
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-500" />
              <h3 className="text-base font-bold text-foreground">Export Curated Library</h3>
            </div>
            <DesignTokenExporter data={{ colors: favoriteColors }} />
          </div>
        </div>
      ) : (
        <div className="bg-secondary/20 border border-dashed border-border/80 rounded-xl p-12 text-center flex flex-col items-center justify-center min-h-[300px] max-w-3xl">
          <FolderHeart className="w-12 h-12 text-muted-foreground/60 mb-3" />
          <h3 className="text-base font-bold text-foreground">Library is empty</h3>
          <p className="text-xs text-muted-foreground/80 mt-1 max-w-sm">
            Click the heart icons on colors generated by the website inspector or image analyzer to save them here.
          </p>
        </div>
      )}
    </div>
  );
}
